# Generated by Django 2.0.7 on 2019-12-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_auto_20191218_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='reading',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
